#TAREA 5.                                     13-04-2025
#XOR resuelto con 16 neuronas en la capa oculta en Keras      
#POSGRADO EN INGENIERÍA AGRÍCOLA Y USO INTEGRAL DEL AGUA
#BALTAZAR LÓPEZ VELASCO

In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
# Datos de entrada
training_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Datos de salida
target_data = np.array([[0], [1], [1], [0]])

In [ ]:
print(training_data)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [ ]:
print(target_data)

[[0]
 [1]
 [1]
 [0]]


Declaramos la RNA con Keras

In [10]:
# Para resolver el problema de la or-exclusivo (XOR) se va a resolver con
# 16 neuronas en la capa oculta de Keras

model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [11]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 16)             │            48 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 65 (260.00 B)

 Trainable params: 65 (260.00 B)

 Non-trainable params: 0 (0.00 B)

HYPERPARÁMETROS

In [13]:
# HYPERPARÁMETROS
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['binary_accuracy'])

In [14]:
# ENTRENAMOS
model.fit(training_data, target_data, epochs=2500, verbose=2)

Epoch 1/2500
1/1 - 2s - 2s/step - binary_accuracy: 0.5000 - loss: 0.2750
Epoch 2/2500
1/1 - 0s - 65ms/step - binary_accuracy: 0.2500 - loss: 0.2743
Epoch 3/2500
1/1 - 0s - 144ms/step - binary_accuracy: 0.2500 - loss: 0.2736
Epoch 4/2500
1/1 - 0s - 67ms/step - binary_accuracy: 0.2500 - loss: 0.2729
Epoch 5/2500
1/1 - 0s - 65ms/step - binary_accuracy: 0.2500 - loss: 0.2722
Epoch 6/2500
1/1 - 0s - 145ms/step - binary_accuracy: 0.2500 - loss: 0.2715
Epoch 7/2500
1/1 - 0s - 134ms/step - binary_accuracy: 0.2500 - loss: 0.2708
Epoch 8/2500
1/1 - 0s - 84ms/step - binary_accuracy: 0.2500 - loss: 0.2701
Epoch 9/2500
1/1 - 0s - 137ms/step - binary_accuracy: 0.2500 - loss: 0.2695
Epoch 10/2500
1/1 - 0s - 141ms/step - binary_accuracy: 0.2500 - loss: 0.2688
Epoch 11/2500
1/1 - 0s - 82ms/step - binary_accuracy: 0.2500 - loss: 0.2682
Epoch 12/2500
1/1 - 0s - 132ms/step - binary_accuracy: 0.2500 - loss: 0.2676
Epoch 13/2500
1/1 - 0s - 57ms/step - binary_accuracy: 0.2500 - loss: 0.2669
Epoch 14/2500
1/1

Evaluación del modelo

In [15]:
# EVALUAMOS
scores = model.evaluate(training_data, target_data)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
print(model.predict(training_data).round())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 261ms/step - binary_accuracy: 1.0000 - loss: 0.0063

compile_metrics: 100.00%
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
[[0.]
 [1.]
 [1.]
 [0.]]


Pesos y sesgo

In [16]:
# PESOS Y SESGO

print("\nPesos y sesgos del modelo:")
for i, layer in enumerate(model.layers):
    weights, biases = layer.get_weights()
    print(f"\nCapa {i + 1} - Pesos:\n{weights}")
    print(f"Capa {i + 1} - Sesgos:\n{biases}")


Pesos y sesgos del modelo:

Capa 1 - Pesos:
[[ 0.7072441   1.2540581   0.67554975 -0.56854403 -0.00518828  0.7241796
  -0.4266922   0.61681634  1.3905421   0.60325384 -0.2152138   0.7553093
  -0.11571828  0.89041734  0.9337613   0.10076079]
 [ 0.70717454  2.1088994   0.67545664 -0.5690295  -0.5120834   0.72411317
  -0.31760994  0.616672   -1.3902931   0.60329074 -0.3972069   0.7553063
  -0.5607327   0.8903575   0.93372035 -0.4763882 ]]
Capa 1 - Sesgos:
[-7.0724833e-01 -3.2777527e-05 -6.7545295e-01  0.0000000e+00
 -1.0362852e-02 -7.2418070e-01  0.0000000e+00 -6.1675972e-01
 -6.7129375e-05 -6.0330617e-01  0.0000000e+00 -7.5525570e-01
  0.0000000e+00 -8.9041072e-01 -9.3375242e-01 -1.1461268e-01]

Capa 2 - Pesos:
[[-1.4631042 ]
 [ 2.2027843 ]
 [-1.7149364 ]
 [-0.02726233]
 [-0.13829786]
 [-1.4507198 ]
 [ 0.22389936]
 [-1.9027934 ]
 [ 1.5605539 ]
 [-1.3376292 ]
 [ 0.5822084 ]
 [-1.3868564 ]
 [-0.29386654]
 [-1.437543  ]
 [-1.222526  ]
 [-0.12350177]]
Capa 2 - Sesgos:
[-1.8523443]
