In [ ]:
# TAREA 3. or-exclusivo (XOR)      01-04-2025
# POSGRADO EN INGENIERÍA AGRÍCOLA Y USO INTEGRAL DEL AGUA
# BALTAZAR LÓPEZ VELASCO
# Los pares de entrada/objetivo para la puerta XOR son:
# {p1 = [0; 0], t1 = 0}
# {p1 = [0; 1], t1 = 1}
# {p1 = [1; 0], t1 = 1}
# {p1 = [1; 1], t1 = 0}

In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
# Datos de entrada
training_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Datos de salida
target_data = np.array([[0], [1], [1], [0]])

In [ ]:
print(training_data)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [ ]:
print(target_data)

[[0]
 [1]
 [1]
 [0]]


In [ ]:
# Para resolver el problema de la or-exclusivo (XOR) se propone usar dos neuronas en la primera capa para crear dos limites de decisión
# Usando Keras para declarar la NN (Neural Network)
model = Sequential()
model.add(Dense(2, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:

# HYPERPARÁMETROS
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['binary_accuracy'])

In [ ]:
# ENTRENAMOS
model.fit(training_data, target_data, epochs=2500, verbose=2)

Epoch 1/2500
1/1 - 1s - 576ms/step - binary_accuracy: 0.7500 - loss: 0.2388
Epoch 2/2500
1/1 - 0s - 32ms/step - binary_accuracy: 0.7500 - loss: 0.2387
Epoch 3/2500
1/1 - 0s - 32ms/step - binary_accuracy: 0.7500 - loss: 0.2386
Epoch 4/2500
1/1 - 0s - 31ms/step - binary_accuracy: 1.0000 - loss: 0.2385
Epoch 5/2500
1/1 - 0s - 59ms/step - binary_accuracy: 1.0000 - loss: 0.2384
Epoch 6/2500
1/1 - 0s - 28ms/step - binary_accuracy: 1.0000 - loss: 0.2383
Epoch 7/2500
1/1 - 0s - 29ms/step - binary_accuracy: 1.0000 - loss: 0.2382
Epoch 8/2500
1/1 - 0s - 62ms/step - binary_accuracy: 1.0000 - loss: 0.2381
Epoch 9/2500
1/1 - 0s - 33ms/step - binary_accuracy: 1.0000 - loss: 0.2381
Epoch 10/2500
1/1 - 0s - 61ms/step - binary_accuracy: 1.0000 - loss: 0.2380
Epoch 11/2500
1/1 - 0s - 28ms/step - binary_accuracy: 1.0000 - loss: 0.2379
Epoch 12/2500
1/1 - 0s - 28ms/step - binary_accuracy: 1.0000 - loss: 0.2378
Epoch 13/2500
1/1 - 0s - 61ms/step - binary_accuracy: 1.0000 - loss: 0.2377
Epoch 14/2500
1/1 - 

In [ ]:
# EVALUAMOS
scores = model.evaluate(training_data, target_data)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
print(model.predict(training_data).round())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - binary_accuracy: 1.0000 - loss: 0.0091

compile_metrics: 100.00%
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step
[[0.]
 [1.]
 [1.]
 [0.]]


In [ ]:
# PESOS Y SESGO

print("\nPesos y sesgos del modelo:")
for i, layer in enumerate(model.layers):
    weights, biases = layer.get_weights()
    print(f"\nCapa {i + 1} - Pesos:\n{weights}")
    print(f"Capa {i + 1} - Sesgos:\n{biases}")


Pesos y sesgos del modelo:

Capa 1 - Pesos:
[[ 2.0312252 -1.5980879]
 [-2.0311062  1.5980169]]
Capa 1 - Sesgos:
[1.8127685e-07 3.3524877e-05]

Capa 2 - Pesos:
[[2.1972268]
 [2.8484018]]
Capa 2 - Sesgos:
[-2.20964]
